### ISSUE TITLE
Infinite scroll is broken 

### ISSUE THREAD

**Issue by dirkcuys** [p2pu/p2pu-components#37]
on on https://www.p2pu.org/en/courses/ and learningcircles.p2pu.org

**Comment by s-kennedy** [comment]
@dirkcuys i just pulled p2pu-website and learning-circles from master and the infinite scroll is working on both of them so can you push them to staging so I can test there too? Thanks!

**Comment by GrifP** [comment]
This issue was brought to our attention again on Thursday by the Providence team going through the learning about learning circles course.
